# Generated by Django 5.0.4 on 2024-05-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphvisualiztion', '0004_alter_objective_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objective',
            old_name='related_course',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_category',
            field=models.CharField(choices=[('Compulsory', 'Compulsory'), ('Elective', 'Elective')], max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
        migrations.AlterField(
            model_name='objective',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='level',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Trajectory',
            fields=[
                ('trajectory_id', models.AutoField(primary_key=True, serialize=False)),
                ('trajectory_name', models.CharField(max_length=30)),
                ('objective', models.TextField()),
                ('related_course_objectives', models.ManyToManyField(to='graphvisualization.objective')),
            ],
        ),
        migrations.DeleteModel(
            name='Trajectories',
        ),
    ]
