# Generated by Django 5.0.4 on 2024-05-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphvisualiztion', '0005_rename_related_course_objective_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
