# Generated by Django 5.0.4 on 2024-05-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphvisualiztion', '0010_alter_trajectory_trajectory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
