# Generated by Django 5.0.4 on 2024-06-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphvisualiztion', '0011_alter_course_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='objective_id',
            field=models.IntegerField(default=0),
        ),
    ]
