# Generated by Django 5.0.4 on 2024-06-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphvisualiztion', '0012_objective_objective_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='graphvisualiztion/CSV/'),
        ),
    ]
