# Generated by Django 5.0.4 on 2024-06-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphvisualiztion', '0014_alter_course_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='graphvisualiztion/CSV/'),
        ),
    ]
