# Generated by Django 5.0.4 on 2024-06-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphvisualiztion', '0016_alter_course_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='source',
            field=models.CharField(blank=True, choices=[('ACM', 'ACM'), ('UvA', 'UvA')], max_length=10, null=True),
        ),
    ]
