# Generated by Django 5.0.4 on 2024-06-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphvisualiztion', '0018_alter_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_category',
            field=models.CharField(blank=True, choices=[('Compulsory', 'Compulsory'), ('Elective', 'Elective')], max_length=10, null=True),
        ),
    ]
